version: 0.2

# AWS CodeBuild Build Specification for Java Spring Boot + Angular
# Optimized for t2.micro (1GB RAM)

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18
    commands:
      - echo "Installing build tools..."
      - echo "Java version:" && java -version
      - echo "Node version:" && node --version
      - echo "Maven version:" && mvn --version
      
  pre_build:
    commands:
      - echo "Building Angular frontend..."
      - cd frontend
      - npm install -g @angular/cli@17
      - npm install
      - npx ng build --configuration production
      - echo "Frontend build complete"
      - cd ..
      
  build:
    commands:
      - echo "Building Spring Boot backend..."
      - cd backend
      - mvn clean package -DskipTests=false
      - echo "Backend build complete"
      - ls -la target/
      - cd ..
      
  post_build:
    commands:
      - echo "Build completed successfully"
      - echo "Preparing artifacts..."

artifacts:
  files:
    - '**/*'
  name: BuildArtifact-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    - '/root/.m2/**/*'           # Maven dependencies
    - 'frontend/node_modules/**/*'  # npm packages
